### ISSUE TITLE
Failed to connect to reader instance

### ISSUE THREAD

**Issue by nalininagarathinam** [aws/aws-advanced-jdbc-wrapper#529] opened 2023-07-07 11:44 UTC
### Describe the bug

Tried to use the "readwritesplitting" plugin from aws-advanced-jdbc-wrapper.  Followed the example, https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/a2684f3d4acc0960c1feb49b965f632e95f4dc7b/examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingPostgresExample.java

The plugin is not working because it couldn't able to connect to reader instance. As the plugin internally refers to the host name (accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxx) to connect to reader instance. It is failing to connect with host name. In our cloud platform, we connect with endpoints (accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxx-us-central-2.rds.amazonaws.com) between the services instead of hostname. 

Below are error logs,

2023-07-05 06:00:16 26186 [main] WARN  s.a.j.p.r.ReadWriteSplittingPlugin correlationId= sessionid=  - Failed to connect to reader host: 'accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/'
2023-07-05 06:00:16 26187 [main] TRACE s.a.j.DriverConnectionProvider correlationId= sessionid=  - Connecting to jdbc:postgresql://accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/testdb with properties: [password] [targetDataSourceClassName] org.postgresql.ds.PGSimpleDataSource[user]
2023-07-05 06:00:16 26192 [main] WARN  s.a.j.p.r.ReadWriteSplittingPlugin correlationId= sessionid=  - Failed to switch to a reader; the current writer will be used as a fallback: 'test-db.cluster-XYZ.us-central-2.rds.amazonaws.com:5432/' 

Is it any possible way to override the hostname ?

### Expected Behavior

We expect that plugin should provide the facility to override the instance hostname or enable options to connect with endpoints.

### What plugins are used? What other connection properties were set?

readwritesplitting

### Current Behavior

2023-07-05 06:00:16 26186 [main] WARN  s.a.j.p.r.ReadWriteSplittingPlugin correlationId= sessionid=  - Failed to connect to reader host: 'accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/'
2023-07-05 06:00:16 26187 [main] TRACE s.a.j.DriverConnectionProvider correlationId= sessionid=  - Connecting to jdbc:postgresql://accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/testdb with properties: [password] [targetDataSourceClassName] org.postgresql.ds.PGSimpleDataSource[user]
2023-07-05 06:00:16 26192 [main] WARN  s.a.j.p.r.ReadWriteSplittingPlugin correlationId= sessionid=  - Failed to switch to a reader; the current writer will be used as a fallback: 'test-db.cluster-XYZ.us-central-2.rds.amazonaws.com:5432/' 

### Reproduction Steps

As mentioned above.

### Possible Solution

Options to override the hostname or url.

### The AWS Advanced JDBC Driver version used

2.2.1

### JDK version used

17

### Operating System and version

Mac/Linux

**Comment by crystall-bitquill** [comment] 2023-07-08 01:18
Hi @nalininagarathinam,

Thanks for raising this issue.

How are you configuring your datasource? The example below shows how users might configure a simple datasource to make a connection:

```java
AwsWrapperDataSource ds = new AwsWrapperDataSource();
ds.setJdbcProtocol("jdbc:postgresql:");
ds.setTargetDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
ds.setDatabase("employees");
ds.setServerPort("5432");
ds.setServerName("db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com");

Properties targetDataSourceProps = new Properties();
targetDataSourceProps.setProperty(PropertyDefinition.PLUGINS.name, "readWriteSplitting,failover,efm");
ds.setTargetDataSourceProperties(targetDataSourceProps);

try (final Connection conn = ds.getConnection(USER, PASSWORD)) {
    // ...
}
```

Are there any notable differences between the example and how your datasource is configured? 

AwsWrapperDataSource objects can also set the JDBC URL to connect, like this:
```java
final String POSTGRESQL_CONNECTION_STRING =
      "jdbc:aws-wrapper:postgresql://test-db.cluster-XYZ.us-east-2.rds.amazonaws.com:5432/readWriteSplittingExample";

AwsWrapperDataSource ds = new AwsWrapperDataSource();
ds.setTargetDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
ds.setJdbcUrl(POSTGRESQL_CONNECTION_STRING);

Properties targetDataSourceProps = new Properties();
targetDataSourceProps.setProperty(PropertyDefinition.PLUGINS.name, "readWriteSplitting,failover,efm");
ds.setTargetDataSourceProperties(targetDataSourceProps);

try (final Connection conn = ds.getConnection(USER, PASSWORD)) {
    // ...
}
```

Additionally, [this page](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DataSource.md) may be helpful as it contains more details on using datasources with the AWS JDBC Driver.

**Comment by nalininagarathinam** [comment] 2023-07-09 23:39
Hi @crystall-bitquill ,

Thanks for replying on this issue.
Have used the below example code to connect to our aurora postgresql database and its failed to reader instance  with the error because it uses the hostname to connect to reader instance. It is not working in our platform as we use only the endpoints. Is there any possible way to override this hostname?

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/a2684f3d4acc0960c1feb49b965f632e95f4dc7b/examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingPostgresExample.java

ERROR:
2023-07-05 06:00:16 26186 [main] WARN s.a.j.p.r.ReadWriteSplittingPlugin correlationId= sessionid= - Failed to connect to reader host: 'accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/'
2023-07-05 06:00:16 26187 [main] TRACE s.a.j.DriverConnectionProvider correlationId= sessionid= - Connecting to jdbc:postgresql://accid-env-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/testdb with properties: [password] [targetDataSourceClassName] org.postgresql.ds.PGSimpleDataSource[user]
2023-07-05 06:00:16 26192 [main] WARN s.a.j.p.r.ReadWriteSplittingPlugin correlationId= sessionid= - Failed to switch to a reader; the current writer will be used as a fallback: 'test-db.cluster-XYZ.us-central-2.rds.amazonaws.com:5432/'

**Comment by crystall-bitquill** [comment] 2023-07-14 16:53
Hi @nalininagarathinam,

I wanted to check in and see how things were going. Were you able to connect to the reader instance?

**Comment by nalininagarathinam** [comment] 2023-07-19 01:44
Hi @crystall-bitquill 
I am able to connect to the reader instance now by using the clusterInstanceHostPattern.
But noticed that the SELECT queries are not redirected to reader instance and still it goes to writer instance.
Could you please explain what will be possible issue?
Thanks,

**Comment by nalininagarathinam** [comment] 2023-07-19 22:15
Hi @crystall-bitquill , could you please advise on how to set the readonly method in the spring hibernate jpa application?

**Comment by karenc-bq** [comment] 2023-07-19 23:28
Hi @nalininagarathinam, how are you configuring your datasources for your application? If you are doing it programatically, you can try `datasource.setReadOnly(true);`. This line comes from [this example](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/a2684f3d4acc0960c1feb49b965f632e95f4dc7b/examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingSpringJdbcTemplateExample.java#L108).

**Comment by crystall-bitquill** [comment] 2023-08-29 22:28
Hi @nalininagarathinam,

I wanted to check in and see if you were able to connect to the reader instance. If there are no further updates on this ticket in the next few days, it will be closed. If you have other questions or concerns please feel free to reopen this issue or to create a new one.

Thank you!

**Comment by davecramer** [comment] 2023-09-01 15:43
@crystall-bitquill are you able to repro this bug if you don't connect to the cluster endpoint ?

**Comment by crystall-bitquill** [comment] 2023-09-01 22:00
Hi @davecramer, I wasn't able to repro this bug. I tried connecting using the IP address instead of the cluster endpoint and was able to connect and switch to reader instances as expected.

**Comment by aaron-congo** [comment] 2024-09-03 21:31
Hi @nalininagarathinam, as @crystall-bitquill mentioned earlier, I will be closing this ticket because we have been unable to reproduce the issue and we have not received any updates from you. However, if you need further assistance, please feel free to reopen this issue or create a new one. Thanks!

**Closed by aaron-congo** 2024-09-03 21:31 UTC
Labels: bug
