### ISSUE TITLE
Running the limitless performance test with the AWS wrapper results in a CPU spike

### ISSUE THREAD

**Issue by jkwuc89** [aws/aws-advanced-jdbc-wrapper#1218] opened 2024-12-10 18:38 UTC
### Describe the bug

I configured JMeter inside my Windows Server 2022 EC2 instance to run the performance tests using the driver without any plugins and the driver with the limitless plugin.

My Aurora limitless instance is configured as follows:
```
* Engine: 16.4-limitless
* Minimum capacity: 64 ACUs (128 GiB)
* Maximum capacity: 1501 ACUs (3002 GiB)
* Transaction routers: 4
* Shards: 4
    * Additional routers and shards beyond the default of 2 for each were created using the following.
        https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/limitless-add-router.html
        https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/limitless-shard-split.html
* Region: us-east-2
```

The screencast below shows the tests running with the base driver. Observe that JMeter is able to update itself with the test progress and the CPU usage does not spike.

https://github.com/user-attachments/assets/fdb44986-e109-49aa-9749-ec698e5523d0

The screencast below shows the tests running with the AWS wrapper and the limitless plugin. Observe that JMeter no longer updates itself, and Task Manager no longer updates itself. When the test completes, Task Manager shows that the CPU usage spiked to 100% during the test run.

https://github.com/user-attachments/assets/a2a00d3f-23f4-414f-8109-d89def48f41b

The screencast below shows the tests running with the AWS wrapper with no plugins. Observe that the CPU still spikes but not as severe as when the limitless plugin is used.

https://github.com/user-attachments/assets/4556d0df-30e7-48fe-90c8-68fbe3d6cc60

### Expected Behavior

Using the AWS wrapper should not cause the CPU utilization to spike. CPU utilization should be more or less comparable to using base driver without the AWS wrapper.

### What plugins are used? What other connection properties were set?

limitless

### Current Behavior

Please refer to the bug description above.

### Reproduction Steps

1. Configure JMeter to run the performance tests.
2. The start of each screencast above shows how the JDBC connections should be configured. Attached below is the JMeter test plan that can be used as a starting point.
3. Run the JMeter test.

### The AWS Advanced JDBC Driver version used

2.5.3

### JDK version used

OpenJDK 64-Bit Server VM Corretto-17.0.13.11.1 (build 17.0.13+11-LTS, mixed mode, sharing)

### Operating System and version

Windows 2022 Server EC2 m7a.xlarge (4 vCPUs, 16 GB of memory)

**Comment by aaronchung-bitquill** [comment] 2024-12-18 09:31
Hello teammate! ;)

For the expected behaviour of the AWS JDBC Driver, it is expected to introduce extra overhead on top of the underlying driver as it adds extra functionality on top. The same goes for the Limitless plugin.

To sanity check though, I ran a few rough load tests in an example application to see if I could see replicate these performance issues.

Test setup:
- Spring Boot web application
  - HTTP GET Endpoint that directly instantiates a new (database) connection object and queries "SELECT * from aurora_db_instance_identifier()"
  - No connection pooling as specified above
- Locust Load Delivery
   - 500 users/threads
   - 50 user/thread ramp-up per second
- JProfiler
  - monitoring the Spring Boot web application

The use of JProfiler here I think will give us a cleaner look at the driver performance with less noise. 

Cases
1. Web application set up with PG JDBC Driver
2. Web application set up with AWS JDBC Driver wrapping PG JDBC Driver with no plugins enabled
3. Web application set up with AWS JDBC Driver wrapping PG JDBC Driver with only Limitless plugin enabled

Observations
Case 1:Web application using PG JDBC Driver
Locust Stats: (Please take this with a grain of salt since network latency can skew things)
- ~150 RPS
- Average Response Time: ~1580ms
- 95th Percentile Response Time: ~4700ms
JProfiler Stats: 
- Memory Usage:
  - Commited Memory: ~1.3GB
  - Used Memory: 0.6 ~ 1.1 GB
- CPU Usage:
  - Process Load: ~18%
  - System Load: ~45%

Case 2:Web application using AWS JDBC Driver with no plugins enabled
Locust Stats: (Please take this with a grain of salt since network latency can skew things)
- ~ 150 RPS
- Average Response Time: ~1500ms
- 95th Percentile Response Time: ~4700ms
JProfiler Stats: 
- Memory Usage:
  - Commited Memory: ~3.7GB
  - Used Memory: 0.6GB ~ 3.2 GB (regular spikes corresponding to GC activity)
- CPU Usage:
  - Process Load: ~18%
  - System Load: ~40%

Case 3:Web application using AWS JDBC Driver with only Limitless plugin enabled
Locust Stats: (Please take this with a grain of salt since network latency can skew things)
- ~ 150 RPS
- Average Response Time: ~1400ms
- 95th Percentile Response Time: ~4700ms
JProfiler Stats: 
- Memory Usage:
  - Commited Memory: ~5.9GB
  - Used Memory: 0.6GB ~ 4.7 GB (regular spikes corresponding to GC activity)
- CPU Usage:
  - Process Load: ~18%
  - System Load: ~45%

Conclusions:
The web application response time stats were also roughly the same across the different driver set ups. 
Memory usage however was more with the AWS JDBC Driver, and even more so with the Limitless plugin enabled. 
Contrary to your findings, the CPU usage did not change much across the different driver set ups.

I'll be closing this ticket for now, but I'll put a ticket in our backlog so we can take a closer look at this and with a similar environment. 

Thanks,
Aaron

**Closed** 2024-12-18 09:34 UTC
Labels: bug
