### ISSUE TITLE
Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by jrschwartz** [aws/aws-advanced-jdbc-wrapper#912] opened 2024-03-02 17:06 UTC
### Describe the bug

After upgrading my rds from 5.7 to 8.0.36, I am not able to connect via my java applications on ec2 linux. It works fine from windows. First I tried MySQL Connector/J and everything I read said that Amazon discontinued query_cache_size, so I thought it was an issue with the connector. Then I found and implemented the AWS JDBC Driver, figuring it would know about the changes, but I still get the Exception and I'm getting very frustrated.

### Expected Behavior

I am just trying to create a connection

### What plugins are used? What other connection properties were set?

jdbcString=jdbc:aws-wrapper:mysql://[server].us-east-1.rds.amazonaws.com/[schema]?user=[user]&password=[password]&useSSL=false

### Current Behavior

java.sql.SQLException: Unknown system variable 'query_cache_size'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:695)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
        at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2041)
        at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1994)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1429)
        at com.mysql.cj.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:2893)
        at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:2428)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1797)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1653)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:662)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:352)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221)
        at software.amazon.jdbc.DriverConnectionProvider.connect(DriverConnectionProvider.java:125)
        at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connectInternal(DefaultConnectionPlugin.java:203)
        at software.amazon.jdbc.plugin.DefaultConnectionPlugin.connect(DefaultConnectionPlugin.java:191)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:353)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$null$0(ConnectionPluginManager.java:243)
        at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:220)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$1(ConnectionPluginManager.java:243)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:248)
        at software.amazon.jdbc.plugin.efm2.HostMonitoringConnectionPlugin.connectInternal(HostMonitoringConnectionPlugin.java:234)
        at software.amazon.jdbc.plugin.efm2.HostMonitoringConnectionPlugin.connect(HostMonitoringConnectionPlugin.java:229)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:353)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:247)
        at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:220)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:247)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:248)
        at software.amazon.jdbc.plugin.staledns.AuroraStaleDnsHelper.getVerifiedConnection(AuroraStaleDnsHelper.java:69)
        at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connectInternal(FailoverConnectionPlugin.java:777)
        at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connect(FailoverConnectionPlugin.java:770)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:353)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:247)
        at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:220)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:247)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:248)
        at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.connectInternal(AuroraConnectionTrackerPlugin.java:91)
        at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.connect(AuroraConnectionTrackerPlugin.java:84)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$6(ConnectionPluginManager.java:353)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:247)
        at software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:220)
        at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:247)
        at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:210)
        at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:350)
        at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:160)
        at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:105)
        at software.amazon.jdbc.Driver.connect(Driver.java:176)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at com.astor.research.DataLayer.initializeConnection(DataLayer.java:53)

### Reproduction Steps

conn = DriverManager.getConnection(props.getProperty("jdbcString"));
logger.debug("Connected to MySQL "+props.getProperty("jdbcString"));

### The AWS Advanced JDBC Driver version used

2.3.4

### JDK version used

openjdk version "1.8.0_312"

### Operating System and version

Amazon Linux

**Comment by jrschwartz** [comment] 2024-03-02 18:48
This was a former blue/green deployment, but I already switched it over because it was working from windows and did not see the linux issue until after I made the green live.

**Comment by crystall-bitquill** [comment] 2024-03-07 23:31
Hi @jrschwartz,

Thank you for reaching out and raising this issue.

It looks like the query cache was [deprecated as of MySQL 5.7.20 and was removed in MySQL 8.0](https://dev.mysql.com/doc/refman/5.7/en/query-cache.html).

To confirm, you originally had an RDS MySQL 5.7 database, and not an Aurora MySQL database? And the database version was updated through the blue/green deployment switchover?

You mentioned having tried the MySQL Connector/J first before switching to the AWS JDBC Driver. However, the AWS JDBC Driver requires an underlying driver such as the MySQL Connector/J. To double check, was this the underlying driver used when you set up the AWS JDBC Driver? If so, what version of the MySQL Connector/J were you using?

I tried to reproduce this issue but was not able to obtain this error. I set up a simple java application to be run on an Amazon Linux EC2 instance. The application created a connection and did a get query. I set up an RDS MySQL 5.7 database, then did a blue/green deployment switchover that would upgrade the database engine to 8.0.36. I was able to create a connection and execute a get query without issues. I also tried the same thing with an Aurora database and did not have any problems. I used the latest version of the AWS JDBC Driver along with version 8.3.0 of the MySQL Connector/J as the underlying driver.

Is there anything from this setup that may be missing or significantly different from yours?

**Comment by hsuamz** [comment] 2024-06-25 19:13
Closing this issue since we haven't seen a response. Please feel free to re-open this issue if the issue still persists.

Since Blue/Green Deployments were used, please refer to [documentation](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md#bluegreen-deployments) that goes over some limitations.

Thank you.

**Closed by hsuamz** 2024-06-25 19:13 UTC
Labels: bug, question
