### ISSUE TITLE
Context on "unexpected errors" with Blue/Green deployments

### ISSUE THREAD

**Issue by peternorthphorest** [aws/aws-advanced-jdbc-wrapper#901] opened 2024-02-22 10:42 UTC
### Describe the issue

"please note that even with your application coded to retry the database connection, you may still encounter other unexpected errors"

Is it possible for you to give more context on this in the READme, with regard to Blue/Green deployments? What kind of errors can we expect? Are there known solutions to the unexpected errors?

### Links

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/README.md?plain=1#L119

**Comment by aaronchung-bitquill** [comment] 2024-02-27 22:34
Hello @peternorthphorest 

Since Blue/Green deployment is currently not supported, it has not yet been tested thoroughly with the AWS JDBC Driver. Other than basic connectivity, there are numerous scenarios which have not been verified. As such, we cannot guarantee the driver will work as intended or give more context into what errors are to be expected since we have not tested them. 

I hope that answers your question.

Thank you!

**Comment by hsuamz** [comment] 2024-06-25 19:15
Closing this issue since recent [documentation](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md#bluegreen-deployments) regarding limitations regarding Blue/Green support has been published.

**Closed by hsuamz** 2024-06-25 19:15 UTC
Labels: documentation
