### ISSUE TITLE
This driver is not a drop in replacement for the PostgreSql driver

### ISSUE THREAD

**Issue by smileatom** [aws/aws-advanced-jdbc-wrapper#985] opened 2024-05-07 01:41 UTC
### Describe the bug

The postgres sql driver supports connection options in the url.  This driver does not.
This is not a drop in replacement.  Please remove the language from your marketing brochure.

### Expected Behavior

driver connection options are supported in the datasource url

### What plugins are used? What other connection properties were set?

IAM

### Current Behavior

Unable to parse options....

### Reproduction Steps

add ?options= and any driver option at the end of the datasource url.

### Possible Solution

Support the same behavior as postgres driver.

### The AWS Advanced JDBC Driver version used

any

### JDK version used

any

### Operating System and version

any

**Comment by davecramer** [comment] 2024-05-08 09:33
Can you be more specific as to what the issue is that you are seeing?

**Comment by smileatom** [comment] 2024-05-08 09:37
I would love to, except that, anyone making drop in replacement claims should know what they are replacing.
And because this project DOESNT, it not only shouldnt be making those claims but shouldnt be advertising knock off Postgres drivers.

This is awslabs.  Nobody takes this stuff seriously and putting it in production is a huge mistake.  
Figure it out on your own.  Or stop making the claim.  Or delete this project.

Im not a child like you.

**Comment by hsuamz** [comment] 2024-05-08 20:05
Thank you for the report. Regarding the issue, the following code snippet:

```
public class DatasourceExample {
  public static void main(String[] args) throws SQLException {
    final AwsWrapperDataSource ds = new AwsWrapperDataSource();
    ds.setJdbcUrl("jdbc:aws-wrapper:postgresql://database-pg.cluster-xyz.us-east-2.rds.amazonaws.com/postgres?options=-c%20statement_timeout=1000&wrapperLoggerLevel=all&wrapperPlugins=iam&user=jane_doe&iamRegion=us-east-2");
    ds.setTargetDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
    try (final Connection conn = ds.getConnection();
        final Statement statement = conn.createStatement();
        final ResultSet rs = statement.executeQuery("SELECT * from aurora_db_instance_identifier()")) {
      if (rs.next()) {
        System.out.println(rs.getString(1));
      }
    }
  }
}
```

We can confirm the driver has a parsing issue in particular to `?options=-c%20statement_timeout=1000`. The driver is incorrectly truncating nested connection options when parsing connection URLs. We'll be issuing a fix that resolves this.

Our goal of the driver is to be `drop-in compatible` with the native open-source drivers ([PostgreSQL JDBC Driver](https://github.com/pgjdbc/pgjdbc), [MySQL JDBC Driver](https://github.com/mysql/mysql-connector-j), and [MariaDB JDBC Driver](https://github.com/mariadb-corporation/mariadb-connector-j)) by aiming to minimize changes to only the connection string and working in conjunction with these drivers.

We'll provide an update here when the fix has been merged in.

**Comment by hsuamz** [comment] 2024-05-16 15:29
Thanks for the feedback @DhayanandBaskar.

For visibility, the fix has been merged into our main branch: https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/988

We do provide snapshot builds that will contain the fix. For more information, please refer to here: https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/988

As for an official release, we will be doing a release by the end of the month.

**Comment by smileatom** [comment] 2024-06-05 01:14
Any idea when this release is coming?

**Comment by hsuamz** [comment] 2024-06-05 15:29
@smileatom , we'll be working on the release today and it will be made available this week.

Thank you!

**Comment by aaronchung-bitquill** [comment] 2024-06-06 17:32
Hi @smileatom ,

The fix is now available on the [latest version](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.7/jar) of the AWS Advanced JDBC Driver. 

Could you check it out let us know if the issue still persists?

Thank you!

**Comment by smileatom** [comment] 2024-06-10 19:31
Does not work.  When this driver can parse options as documented in the PG documentation
https://jdbc.postgresql.org/documentation/use/
String url = "jdbc:postgresql://localhost:5432/postgres?options=-c%20search_path=test,public,pg_catalog%20-c%20statement_timeout=90000";
This will not parse due to the encoded spaces.  When this driver parses the above correctly it will will work.

**Comment by aaronchung-bitquill** [comment] 2024-06-11 01:26
Hi @smileatom 

I am having trouble reproducing this issue with the the latest version (2.3.7).

I am using a simple code snippet like the one below. The JDBC URL has the `options` parameter set in the URL and includes encoded spaces. 

```
public class DatasourceExample {
  public static void main(String[] args) throws SQLException {
    final AwsWrapperDataSource ds = new AwsWrapperDataSource();
    ds.setJdbcUrl("jdbc:aws-wrapper:postgresql://database-pg.cluster-xyz.us-east-2.rds.amazonaws.com:5432/postgres?options=-c%20search_path=test,public,pg_catalog%20-c%20statement_timeout=90000&user=someUser&password=somePassword");
    ds.setTargetDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
    try (final Connection conn = ds.getConnection();
        final Statement statement = conn.createStatement();
        final ResultSet rs = statement.executeQuery("SELECT * from aurora_db_instance_identifier()")) {
      if (rs.next()) {
        System.out.println(rs.getString(1));
      }
    }
  }
}
```

I have also debugged down to  [DataSourceConnectionProvider.java:175](https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/DataSourceConnectionProvider.java#L175) where the returned Connection object is made from the target datasource object (`PGSimpleDataSource` in this case). Here, I am seeing that the datasource object has properly set the `options` parameter with the decoded expected value `-c search_path=test,public,pg_catalog -c statement_timeout=90000`.

Can you confirm you are using the latest version (2.3.7) of the AWS Advanced JDBC Wrapper Driver and perhaps provide us a code snippet of how you are using the AWS JDBC Driver?

Thank you!

**Comment by smileatom** [comment] 2024-06-11 02:14
Hi, this is not the way our driver is configured.  You are setting the property explicitly on the driver.  If you configure this as a spring boot 3 datasource in an application yaml file it fails with the same error as the last driver release.  With postgresSQL driver it works fine.

**Comment by aaronchung-bitquill** [comment] 2024-06-11 17:35
Hi @smileatom

I have configured a Spring Boot 3 application with the following application yaml file but unable to reproduce the issue.
```
spring:
  datasource:
    url: jdbc:aws-wrapper:postgresql://database-pg.cluster-xyz.us-east-2.rds.amazonaws.com:5432/postgres?options=-c%20search_path=test,public,pg_catalog%20-c%20statement_timeout=90000
    username: username
    password: password
    driver-class-name: software.amazon.jdbc.Driver
```
Would you be able to share a sample snippet of your configuration, so that I continue investigation to reproduce the issue?

Thank you!

**Comment by smileatom** [comment] 2024-06-11 19:43
Sorry, an old version of the driver was still in the dependency tree.  Retesting and will let you know.

**Comment by smileatom** [comment] 2024-06-11 21:05
This has been fixed.  Thanks for support!

**Comment by aaronchung-bitquill** [comment] 2024-06-11 22:05
Thanks for you confirming that the fix works! This issue will be closed now, but please feel free to reach out again if there are any other questions or concerns.

**Closed by aaronchung-bitquill** 2024-06-11 22:05 UTC
Labels: bug, pending release
